// import { MapTile } from '@/types/Map';

// export const competitiveMap: MapTile[] = [
//   { id: "0-0", position: [0, 0, 0], terrain: "grass", object: null },
//   { id: "0-1", position: [0, 0, 1], terrain: "grass", object: null },
//   { id: "0-2", position: [0, 0, 2], terrain: "grass", object: null },
//   { id: "0-3", position: [0, 0, 3], terrain: "grass", object: null },
//   { id: "0-4", position: [0, 0, 4], terrain: "grass", object: null },
//   { id: "0-5", position: [0, 0, 5], terrain: "grass", object: null },
//   { id: "0-6", position: [0, 0, 6], terrain: "grass", object: null },
//   { id: "0-7", position: [0, 0, 7], terrain: "grass", object: null },
//   { id: "0-8", position: [0, 0, 8], terrain: "grass", object: null },
//   { id: "0-9", position: [0, 0, 9], terrain: "grass", object: "rock", variant: 0 },
//   { id: "0-10", position: [0, 0, 10], terrain: "grass", object: null },
//   { id: "0-11", position: [0, 0, 11], terrain: "grass", object: null },
//   { id: "0-12", position: [0, 0, 12], terrain: "grass", object: null },
//   { id: "0-13", position: [0, 0, 13], terrain: "water", object: null },
//   { id: "0-14", position: [0, 0, 14], terrain: "grass", object: null },
//   { id: "0-15", position: [0, 0, 15], terrain: "grass", object: null },
//   { id: "0-16", position: [0, 0, 16], terrain: "grass", object: null },
//   { id: "0-17", position: [0, 0, 17], terrain: "grass", object: null },
//   { id: "0-18", position: [0, 0, 18], terrain: "grass", object: null },
//   { id: "0-19", position: [0, 0, 19], terrain: "grass", object: null },
//   { id: "1-0", position: [1, 0, 0], terrain: "grass", object: null },
//   { id: "1-1", position: [1, 0, 1], terrain: "grass", object: null },
//   { id: "1-2", position: [1, 0, 2], terrain: "grass", object: null },
//   { id: "1-3", position: [1, 0, 3], terrain: "grass", object: null },
//   { id: "1-4", position: [1, 0, 4], terrain: "grass", object: null },
//   { id: "1-5", position: [1, 0, 5], terrain: "grass", object: null },
//   { id: "1-6", position: [1, 0, 6], terrain: "grass", object: "bush" },
//   { id: "1-7", position: [1, 0, 7], terrain: "grass", object: null },
//   { id: "1-8", position: [1, 0, 8], terrain: "grass", object: null },
//   { id: "1-9", position: [1, 0, 9], terrain: "grass", object: null },
//   { id: "1-10", position: [1, 0, 10], terrain: "grass", object: null },
//   { id: "1-11", position: [1, 0, 11], terrain: "grass", object: null },
//   { id: "1-12", position: [1, 0, 12], terrain: "grass", object: null },
//   { id: "1-13", position: [1, 0, 13], terrain: "grass", object: null },
//   { id: "1-14", position: [1, 0, 14], terrain: "grass", object: null },
//   { id: "1-15", position: [1, 0, 15], terrain: "grass", object: null },
//   { id: "1-16", position: [1, 0, 16], terrain: "grass", object: null },
//   { id: "1-17", position: [1, 0, 17], terrain: "grass", object: null },
//   { id: "1-18", position: [1, 0, 18], terrain: "grass", object: null },
//   { id: "1-19", position: [1, 0, 19], terrain: "grass", object: null },
//   { id: "2-0", position: [2, 0, 0], terrain: "grass", object: null },
//   { id: "2-1", position: [2, 0, 1], terrain: "grass", object: null },
//   { id: "2-2", position: [2, 0, 2], terrain: "grass", object: "tree", variant: 0 },
//   { id: "2-3", position: [2, 0, 3], terrain: "grass", object: "tree", variant: 1 },
//   { id: "2-4", position: [2, 0, 4], terrain: "water", object: "tree", variant: 0 },
//   { id: "2-5", position: [2, 0, 5], terrain: "grass", object: "tree", variant: 0 },
//   { id: "2-6", position: [2, 0, 6], terrain: "grass", object: null },
//   { id: "2-7", position: [2, 0, 7], terrain: "grass", object: "bush" },
//   { id: "2-8", position: [2, 0, 8], terrain: "grass", object: null },
//   { id: "2-9", position: [2, 0, 9], terrain: "grass", object: null },
//   { id: "2-10", position: [2, 0, 10], terrain: "grass", object: null },
//   { id: "2-11", position: [2, 0, 11], terrain: "grass", object: null },
//   { id: "2-12", position: [2, 0, 12], terrain: "grass", object: null },
//   { id: "2-13", position: [2, 0, 13], terrain: "grass", object: null },
//   { id: "2-14", position: [2, 0, 14], terrain: "grass", object: null },
//   { id: "2-15", position: [2, 0, 15], terrain: "grass", object: null },
//   { id: "2-16", position: [2, 0, 16], terrain: "grass", object: null },
//   { id: "2-17", position: [2, 0, 17], terrain: "grass", object: null },
//   { id: "2-18", position: [2, 0, 18], terrain: "grass", object: null },
//   { id: "2-19", position: [2, 0, 19], terrain: "water", object: null },
//   { id: "3-0", position: [3, 0, 0], terrain: "grass", object: null },
//   { id: "3-1", position: [3, 0, 1], terrain: "water", object: null },
//   { id: "3-2", position: [3, 0, 2], terrain: "water", object: null },
//   { id: "3-3", position: [3, 0, 3], terrain: "water", object: null },
//   { id: "3-4", position: [3, 0, 4], terrain: "grass", object: null },
//   { id: "3-5", position: [3, 0, 5], terrain: "grass", object: "bush" },
//   { id: "3-6", position: [3, 0, 6], terrain: "grass", object: "bush" },
//   { id: "3-7", position: [3, 0, 7], terrain: "grass", object: null },
//   { id: "3-8", position: [3, 0, 8], terrain: "grass", object: null },
//   { id: "3-9", position: [3, 0, 9], terrain: "grass", object: null },
//   { id: "3-10", position: [3, 0, 10], terrain: "grass", object: null },
//   { id: "3-11", position: [3, 0, 11], terrain: "grass", object: null },
//   { id: "3-12", position: [3, 0, 12], terrain: "grass", object: null },
//   { id: "3-13", position: [3, 0, 13], terrain: "grass", object: "tree", variant: 0 },
//   { id: "3-14", position: [3, 0, 14], terrain: "grass", object: null },
//   { id: "3-15", position: [3, 0, 15], terrain: "grass", object: null },
//   { id: "3-16", position: [3, 0, 16], terrain: "grass", object: null },
//   { id: "3-17", position: [3, 0, 17], terrain: "grass", object: null },
//   { id: "3-18", position: [3, 0, 18], terrain: "grass", object: "rock", variant: 1 },
//   { id: "3-19", position: [3, 0, 19], terrain: "grass", object: null },
//   { id: "4-0", position: [4, 0, 0], terrain: "water", object: null },
//   { id: "4-1", position: [4, 0, 1], terrain: "water", object: null },
//   { id: "4-2", position: [4, 0, 2], terrain: "water", object: null },
//   { id: "4-3", position: [4, 0, 3], terrain: "grass", object: null },
//   { id: "4-4", position: [4, 0, 4], terrain: "grass", object: null },
//   { id: "4-5", position: [4, 0, 5], terrain: "grass", object: null },
//   { id: "4-6", position: [4, 0, 6], terrain: "grass", object: null },
//   { id: "4-7", position: [4, 0, 7], terrain: "grass", object: null },
//   { id: "4-8", position: [4, 0, 8], terrain: "grass", object: null },
//   { id: "4-9", position: [4, 0, 9], terrain: "grass", object: null },
//   { id: "4-10", position: [4, 0, 10], terrain: "grass", object: null },
//   { id: "4-11", position: [4, 0, 11], terrain: "grass", object: null },
//   { id: "4-12", position: [4, 0, 12], terrain: "grass", object: null },
//   { id: "4-13", position: [4, 0, 13], terrain: "grass", object: "bush" },
//   { id: "4-14", position: [4, 0, 14], terrain: "grass", object: "rock", variant: 3 },
//   { id: "4-15", position: [4, 0, 15], terrain: "grass", object: "rock", variant: 4 },
//   { id: "4-16", position: [4, 0, 16], terrain: "grass", object: null },
//   { id: "4-17", position: [4, 0, 17], terrain: "grass", object: null },
//   { id: "4-18", position: [4, 0, 18], terrain: "grass", object: "bush" },
//   { id: "4-19", position: [4, 0, 19], terrain: "grass", object: null },
//   { id: "5-0", position: [5, 0, 0], terrain: "grass", object: null },
//   { id: "5-1", position: [5, 0, 1], terrain: "grass", object: "rock", variant: 1 },
//   { id: "5-2", position: [5, 0, 2], terrain: "grass", object: null },
//   { id: "5-3", position: [5, 0, 3], terrain: "grass", object: null },
//   { id: "5-4", position: [5, 0, 4], terrain: "grass", object: null },
//   { id: "5-5", position: [5, 0, 5], terrain: "grass", object: null },
//   { id: "5-6", position: [5, 0, 6], terrain: "grass", object: null },
//   { id: "5-7", position: [5, 0, 7], terrain: "grass", object: null },
//   { id: "5-8", position: [5, 0, 8], terrain: "grass", object: null },
//   { id: "5-9", position: [5, 0, 9], terrain: "grass", object: null },
//   { id: "5-10", position: [5, 0, 10], terrain: "grass", object: "rock", variant: 1 },
//   { id: "5-11", position: [5, 0, 11], terrain: "grass", object: null },
//   { id: "5-12", position: [5, 0, 12], terrain: "grass", object: null },
//   { id: "5-13", position: [5, 0, 13], terrain: "grass", object: null },
//   { id: "5-14", position: [5, 0, 14], terrain: "grass", object: null },
//   { id: "5-15", position: [5, 0, 15], terrain: "grass", object:"rock", variant: 3 },
//   { id: "5-16", position: [5, 0, 16], terrain: "grass", object: null },
//   { id: "5-17", position: [5, 0, 17], terrain: "grass", object: null },
//   { id: "5-18", position: [5, 0, 18], terrain: "grass", object: null },
//   { id: "5-19", position: [5, 0, 19], terrain: "grass", object: null },
//   { id: "6-0", position: [6, 0, 0], terrain: "grass", object: null },
//   { id: "6-1", position: [6, 0, 1], terrain: "grass", object: null },
//   { id: "6-2", position: [6, 0, 2], terrain: "grass", object: null },
//   { id: "6-3", position: [6, 0, 3], terrain: "grass", object: null },
//   { id: "6-4", position: [6, 0, 4], terrain: "grass", object: null },
//   { id: "6-5", position: [6, 0, 5], terrain: "grass", object: null },
//   { id: "6-6", position: [6, 0, 6], terrain: "grass", object: null },
//   { id: "6-7", position: [6, 0, 7], terrain: "grass", object: null },
//   { id: "6-8", position: [6, 0, 8], terrain: "grass", object: null },
//   { id: "6-9", position: [6, 0, 9], terrain: "grass", object: null },
//   { id: "6-10", position: [6, 0, 10], terrain: "grass", object: null },
//   { id: "6-11", position: [6, 0, 11], terrain: "grass", object: null },
//   { id: "6-12", position: [6, 0, 12], terrain: "grass", object: null },
//   { id: "6-13", position: [6, 0, 13], terrain: "grass", object: null },
//   { id: "6-14", position: [6, 0, 14], terrain: "grass", object: null },
//   { id: "6-15", position: [6, 0, 15], terrain: "grass", object: null },
//   { id: "6-16", position: [6, 0, 16], terrain: "grass", object: null },
//   { id: "6-17", position: [6, 0, 17], terrain: "grass", object: null },
//   { id: "6-18", position: [6, 0, 18], terrain: "grass", object: null },
//   { id: "6-19", position: [6, 0, 19], terrain: "grass", object: null },
//   { id: "7-0", position: [7, 0, 0], terrain: "grass", object: null },
//   { id: "7-1", position: [7, 0, 1], terrain: "grass", object: null },
//   { id: "7-2", position: [7, 0, 2], terrain: "grass", object: null },
//   { id: "7-3", position: [7, 0, 3], terrain: "grass", object: null },
//   { id: "7-4", position: [7, 0, 4], terrain: "grass", object: null },
//   { id: "7-5", position: [7, 0, 5], terrain: "grass", object: null },
//   { id: "7-6", position: [7, 0, 6], terrain: "grass", object: null },
//   { id: "7-7", position: [7, 0, 7], terrain: "grass", object: null },
//   { id: "7-8", position: [7, 0, 8], terrain: "water", object: null },
//   { id: "7-9", position: [7, 0, 9], terrain: "water", object: null },
//   { id: "7-10", position: [7, 0, 10], terrain: "grass", object: null },
//   { id: "7-11", position: [7, 0, 11], terrain: "grass", object: "tree", variant: 1 },
//   { id: "7-12", position: [7, 0, 12], terrain: "grass", object: "tree", variant: 2 },
//   { id: "7-13", position: [7, 0, 13], terrain: "grass", object: null },
//   { id: "7-14", position: [7, 0, 14], terrain: "grass", object: null },
//   { id: "7-15", position: [7, 0, 15], terrain: "grass", object: null },
//   { id: "7-16", position: [7, 0, 16], terrain: "grass", object: null },
//   { id: "7-17", position: [7, 0, 17], terrain: "grass", object: null },
//   { id: "7-18", position: [7, 0, 18], terrain: "water", object: null },
//   { id: "7-19", position: [7, 0, 19], terrain: "grass", object: null },
//   { id: "8-0", position: [8, 0, 0], terrain: "water", object: null },
//   { id: "8-1", position: [8, 0, 1], terrain: "grass", object: null },
//   { id: "8-2", position: [8, 0, 2], terrain: "grass", object: null },
//   { id: "8-3", position: [8, 0, 3], terrain: "grass", object: "tree", variant: 1 },
//   { id: "8-4", position: [8, 0, 4], terrain: "grass", object: null },
//   { id: "8-5", position: [8, 0, 5], terrain: "grass", object: null },
//   { id: "8-6", position: [8, 0, 6], terrain: "grass", object: null },
//   { id: "8-7", position: [8, 0, 7], terrain: "grass", object: null },
//   { id: "8-8", position: [8, 0, 8], terrain: "grass", object: null },
//   { id: "8-9", position: [8, 0, 9], terrain: "water", object: null },
//   { id: "8-10", position: [8, 0, 10], terrain: "grass", object: null },
//   { id: "8-11", position: [8, 0, 11], terrain: "grass", object: null },
//   { id: "8-12", position: [8, 0, 12], terrain: "grass", object: null },
//   { id: "8-13", position: [8, 0, 13], terrain: "grass", object: null },
//   { id: "8-14", position: [8, 0, 14], terrain: "grass", object: null },
//   { id: "8-15", position: [8, 0, 15], terrain: "grass", object: null },
//   { id: "8-16", position: [8, 0, 16], terrain: "grass", object: null },
//   { id: "8-17", position: [8, 0, 17], terrain: "grass", object: null },
//   { id: "8-18", position: [8, 0, 18], terrain: "grass", object: null },
//   { id: "8-19", position: [8, 0, 19], terrain: "grass", object: null },
//   { id: "9-0", position: [9, 0, 0], terrain: "grass", object: null },
//   { id: "9-1", position: [9, 0, 1], terrain: "grass", object: null },
//   { id: "9-2", position: [9, 0, 2], terrain: "grass", object: null },
//   { id: "9-3", position: [9, 0, 3], terrain: "grass", object: null },
//   { id: "9-4", position: [9, 0, 4], terrain: "grass", object: null },
//   { id: "9-5", position: [9, 0, 5], terrain: "grass", object: null },
//   { id: "9-6", position: [9, 0, 6], terrain: "grass", object: null },
//   { id: "9-7", position: [9, 0, 7], terrain: "grass", object: null },
//   { id: "9-8", position: [9, 0, 8], terrain: "grass", object: null },
//   { id: "9-9", position: [9, 0, 9], terrain: "water", object: null },
//   { id: "9-10", position: [9, 0, 10], terrain: "grass", object: null },
//   { id: "9-11", position: [9, 0, 11], terrain: "grass", object: null },
//   { id: "9-12", position: [9, 0, 12], terrain: "grass", object: null },
//   { id: "9-13", position: [9, 0, 13], terrain: "grass", object: null },
//   { id: "9-14", position: [9, 0, 14], terrain: "grass", object: null },
//   { id: "9-15", position: [9, 0, 15], terrain: "grass", object: null },
//   { id: "9-16", position: [9, 0, 16], terrain: "grass", object: null },
//   { id: "9-17", position: [9, 0, 17], terrain: "grass", object: null },
//   { id: "9-18", position: [9, 0, 18], terrain: "grass", object: null },
//   { id: "9-19", position: [9, 0, 19], terrain: "grass", object: null },
//   { id: "10-0", position: [10, 0, 0], terrain: "grass", object: null },
//   { id: "10-1", position: [10, 0, 1], terrain: "grass", object: null },
//   { id: "10-2", position: [10, 0, 2], terrain: "grass", object: null },
//   { id: "10-3", position: [10, 0, 3], terrain: "grass", object: null },
//   { id: "10-4", position: [10, 0, 4], terrain: "grass", object: null },
//   { id: "10-5", position: [10, 0, 5], terrain: "grass", object: null },
//   { id: "10-6", position: [10, 0, 6], terrain: "grass", object: "rock", variant: 0 },
//   { id: "10-7", position: [10, 0, 7], terrain: "water", object: null },
//   { id: "10-8", position: [10, 0, 8], terrain: "grass", object: null },
//   { id: "10-9", position: [10, 0, 9], terrain: "grass", object: null },
//   { id: "10-10", position: [10, 0, 10], terrain: "grass", object: null },
//   { id: "10-11", position: [10, 0, 11], terrain: "grass", object: null },
//   { id: "10-12", position: [10, 0, 12], terrain: "grass", object: null },
//   { id: "10-13", position: [10, 0, 13], terrain: "grass", object: null },
//   { id: "10-14", position: [10, 0, 14], terrain: "grass", object: null },
//   { id: "10-15", position: [10, 0, 15], terrain: "grass", object: null },
//   { id: "10-16", position: [10, 0, 16], terrain: "grass", object: "rock", variant: 2 },
//   { id: "10-17", position: [10, 0, 17], terrain: "grass", object: null },
//   { id: "10-18", position: [10, 0, 18], terrain: "grass", object: null },
//   { id: "10-19", position: [10, 0, 19], terrain: "grass", object: null },
//   { id: "11-0", position: [11, 0, 0], terrain: "grass", object: null },
//   { id: "11-1", position: [11, 0, 1], terrain: "grass", object: null },
//   { id: "11-2", position: [11, 0, 2], terrain: "grass", object: null },
//   { id: "11-3", position: [11, 0, 3], terrain: "grass", object: null },
//   { id: "11-4", position: [11, 0, 4], terrain: "grass", object: "bush" },
//   { id: "11-5", position: [11, 0, 5], terrain: "grass", object: "rock", variant: 1 },
//   { id: "11-6", position: [11, 0, 6], terrain: "grass", object: null },
//   { id: "11-7", position: [11, 0, 7], terrain: "grass", object: null },
//   { id: "11-8", position: [11, 0, 8], terrain: "grass", object: null },
//   { id: "11-9", position: [11, 0, 9], terrain: "grass", object: "rock", variant: 0 },
//   { id: "11-10", position: [11, 0, 10], terrain: "grass", object: "tree", variant: 0 },
//   { id: "11-11", position: [11, 0, 11], terrain: "grass", object: null },
//   { id: "11-12", position: [11, 0, 12], terrain: "grass", object: null },
//   { id: "11-13", position: [11, 0, 13], terrain: "grass", object: null },
//   { id: "11-14", position: [11, 0, 14], terrain: "grass", object: null },
//   { id: "11-15", position: [11, 0, 15], terrain: "grass", object: null },
//   { id: "11-16", position: [11, 0, 16], terrain: "grass", object: null },
//   { id: "11-17", position: [11, 0, 17], terrain: "grass", object: null },
//   { id: "11-18", position: [11, 0, 18], terrain: "grass", object: null },
//   { id: "11-19", position: [11, 0, 19], terrain: "grass", object: null },
//   { id: "12-0", position: [12, 0, 0], terrain: "grass", object: null },
//   { id: "12-1", position: [12, 0, 1], terrain: "grass", object: null },
//   { id: "12-2", position: [12, 0, 2], terrain: "grass", object: null },
//   { id: "12-3", position: [12, 0, 3], terrain: "grass", object: "bush" },
//   { id: "12-4", position: [12, 0, 4], terrain: "grass", object: null },
//   { id: "12-5", position: [12, 0, 5], terrain: "grass", object: null },
//   { id: "12-6", position: [12, 0, 6], terrain: "grass", object: null },
//   { id: "12-7", position: [12, 0, 7], terrain: "grass", object: null },
//   { id: "12-8", position: [12, 0, 8], terrain: "grass", object: null },
//   { id: "12-9", position: [12, 0, 9], terrain: "grass", object: null },
//   { id: "12-10", position: [12, 0, 10], terrain: "water", object: null },
//   { id: "12-11", position: [12, 0, 11], terrain: "grass", object: null },
//   { id: "12-12", position: [12, 0, 12], terrain: "grass", object: null },
//   { id: "12-13", position: [12, 0, 13], terrain: "grass", object: null },
//   { id: "12-14", position: [12, 0, 14], terrain: "grass", object: "bush" },
//   { id: "12-15", position: [12, 0, 15], terrain: "grass", object: null },
//   { id: "12-16", position: [12, 0, 16], terrain: "water", object: null },
//   { id: "12-17", position: [12, 0, 17], terrain: "grass", object: "tree", variant: 1 },
//   { id: "12-18", position: [12, 0, 18], terrain: "grass", object: null },
//   { id: "12-19", position: [12, 0, 19], terrain: "grass", object: null },
//   { id: "13-0", position: [13, 0, 0], terrain: "grass", object: null },
//   { id: "13-1", position: [13, 0, 1], terrain: "grass", object: null },
//   { id: "13-2", position: [13, 0, 2], terrain: "grass", object: null },
//   { id: "13-3", position: [13, 0, 3], terrain: "grass", object: null },
//   { id: "13-4", position: [13, 0, 4], terrain: "grass", object: null },
//   { id: "13-5", position: [13, 0, 5], terrain: "grass", object: null },
//   { id: "13-6", position: [13, 0, 6], terrain: "grass", object: null },
//   { id: "13-7", position: [13, 0, 7], terrain: "grass", object: null },
//   { id: "13-8", position: [13, 0, 8], terrain: "grass", object: "tree", variant: 0 },
//   { id: "13-9", position: [13, 0, 9], terrain: "grass", object: "bush" },
//   { id: "13-10", position: [13, 0, 10], terrain: "grass", object: null },
//   { id: "13-11", position: [13, 0, 11], terrain: "grass", object: null },
//   { id: "13-12", position: [13, 0, 12], terrain: "grass", object: null },
//   { id: "13-13", position: [13, 0, 13], terrain: "grass", object: null },
//   { id: "13-14", position: [13, 0, 14], terrain: "grass", object: null },
//   { id: "13-15", position: [13, 0, 15], terrain: "grass", object: null },
//   { id: "13-16", position: [13, 0, 16], terrain: "grass", object: null },
//   { id: "13-17", position: [13, 0, 17], terrain: "grass", object: null },
//   { id: "13-18", position: [13, 0, 18], terrain: "grass", object: null },
//   { id: "13-19", position: [13, 0, 19], terrain: "grass", object: "tree", variant: 2 },
//   { id: "14-0", position: [14, 0, 0], terrain: "grass", object: null },
//   { id: "14-1", position: [14, 0, 1], terrain: "grass", object: null },
//   { id: "14-2", position: [14, 0, 2], terrain: "grass", object: null },
//   { id: "14-3", position: [14, 0, 3], terrain: "grass", object: null },
//   { id: "14-4", position: [14, 0, 4], terrain: "grass", object: null },
//   { id: "14-5", position: [14, 0, 5], terrain: "grass", object: "tree", variant: 0 },
//   { id: "14-6", position: [14, 0, 6], terrain: "grass", object: null },
//   { id: "14-7", position: [14, 0, 7], terrain: "grass", object: null },
//   { id: "14-8", position: [14, 0, 8], terrain: "grass", object: null },
//   { id: "14-9", position: [14, 0, 9], terrain: "grass", object: null },
//   { id: "14-10", position: [14, 0, 10], terrain: "grass", object: null },
//   { id: "14-11", position: [14, 0, 11], terrain: "grass", object: null },
//   { id: "14-12", position: [14, 0, 12], terrain: "grass", object: null },
//   { id: "14-13", position: [14, 0, 13], terrain: "grass", object: "rock", variant: 1 },
//   { id: "14-14", position: [14, 0, 14], terrain: "grass", object: null },
//   { id: "14-15", position: [14, 0, 15], terrain: "grass", object: null },
//   { id: "14-16", position: [14, 0, 16], terrain: "grass", object: null },
//   { id: "14-17", position: [14, 0, 17], terrain: "grass", object: null },
//   { id: "14-18", position: [14, 0, 18], terrain: "water", object: null },
//   { id: "14-19", position: [14, 0, 19], terrain: "grass", object: null },
//   { id: "15-0", position: [15, 0, 0], terrain: "grass", object: null },
//   { id: "15-1", position: [15, 0, 1], terrain: "grass", object: null },
//   { id: "15-2", position: [15, 0, 2], terrain: "grass", object: null },
//   { id: "15-3", position: [15, 0, 3], terrain: "grass", object: null },
//   { id: "15-4", position: [15, 0, 4], terrain: "grass", object: null },
//   { id: "15-5", position: [15, 0, 5], terrain: "grass", object: null },
//   { id: "15-6", position: [15, 0, 6], terrain: "grass", object: "bush" },
//   { id: "15-7", position: [15, 0, 7], terrain: "grass", object: null },
//   { id: "15-8", position: [15, 0, 8], terrain: "grass", object: null },
//   { id: "15-9", position: [15, 0, 9], terrain: "grass", object: null },
//   { id: "15-10", position: [15, 0, 10], terrain: "grass", object: null },
//   { id: "15-11", position: [15, 0, 11], terrain: "grass", object: null },
//   { id: "15-12", position: [15, 0, 12], terrain: "grass", object: null },
//   { id: "15-13", position: [15, 0, 13], terrain: "grass", object: null },
//   { id: "15-14", position: [15, 0, 14], terrain: "grass", object: null },
//   { id: "15-15", position: [15, 0, 15], terrain: "grass", object: null },
//   { id: "15-16", position: [15, 0, 16], terrain: "grass", object: null },
//   { id: "15-17", position: [15, 0, 17], terrain: "grass", object: null },
//   { id: "15-18", position: [15, 0, 18], terrain: "grass", object: null },
//   { id: "15-19", position: [15, 0, 19], terrain: "grass", object: null },
//   { id: "16-0", position: [16, 0, 0], terrain: "grass", object: null },
//   { id: "16-1", position: [16, 0, 1], terrain: "grass", object: "rock", variant: 0 },
//   { id: "16-2", position: [16, 0, 2], terrain: "grass", object: null },
//   { id: "16-3", position: [16, 0, 3], terrain: "water", object: null },
//   { id: "16-4", position: [16, 0, 4], terrain: "grass", object: null },
//   { id: "16-5", position: [16, 0, 5], terrain: "grass", object: null },
//   { id: "16-6", position: [16, 0, 6], terrain: "grass", object: null },
//   { id: "16-7", position: [16, 0, 7], terrain: "grass", object: null },
//   { id: "16-8", position: [16, 0, 8], terrain: "grass", object: null },
//   { id: "16-9", position: [16, 0, 9], terrain: "grass", object: null },
//   { id: "16-10", position: [16, 0, 10], terrain: "grass", object: null },
//   { id: "16-11", position: [16, 0, 11], terrain: "grass", object: null },
//   { id: "16-12", position: [16, 0, 12], terrain: "grass", object: null },
//   { id: "16-13", position: [16, 0, 13], terrain: "grass", object: null },
//   { id: "16-14", position: [16, 0, 14], terrain: "grass", object: null },
//   { id: "16-15", position: [16, 0, 15], terrain: "grass", object: null },
//   { id: "16-16", position: [16, 0, 16], terrain: "grass", object: null },
//   { id: "16-17", position: [16, 0, 17], terrain: "grass", object: null },
//   { id: "16-18", position: [16, 0, 18], terrain: "grass", object: null },
//   { id: "16-19", position: [16, 0, 19], terrain: "grass", object: null },
//   { id: "17-0", position: [17, 0, 0], terrain: "grass", object: null },
//   { id: "17-1", position: [17, 0, 1], terrain: "grass", object: null },
//   { id: "17-2", position: [17, 0, 2], terrain: "grass", object: null },
//   { id: "17-3", position: [17, 0, 3], terrain: "grass", object: "rock", variant: 2 },
//   { id: "17-4", position: [17, 0, 4], terrain: "grass", object: "rock", variant: 2 },
//   { id: "17-5", position: [17, 0, 5], terrain: "grass", object: "tree", variant: 0 },
//   { id: "17-6", position: [17, 0, 6], terrain: "grass", object: null },
//   { id: "17-7", position: [17, 0, 7], terrain: "grass", object: null },
//   { id: "17-8", position: [17, 0, 8], terrain: "grass", object: null },
//   { id: "17-9", position: [17, 0, 9], terrain: "grass", object: null },
//   { id: "17-10", position: [17, 0, 10], terrain: "grass", object: "bush" },
//   { id: "17-11", position: [17, 0, 11], terrain: "grass", object: null },
//   { id: "17-12", position: [17, 0, 12], terrain: "grass", object: "tree", variant: 2 },
//   { id: "17-13", position: [17, 0, 13], terrain: "grass", object: null },
//   { id: "17-14", position: [17, 0, 14], terrain: "grass", object: null },
//   { id: "17-15", position: [17, 0, 15], terrain: "grass", object: null },
//   { id: "17-16", position: [17, 0, 16], terrain: "grass", object: null },
//   { id: "17-17", position: [17, 0, 17], terrain: "grass", object: null },
//   { id: "17-18", position: [17, 0, 18], terrain: "grass", object: null },
//   { id: "17-19", position: [17, 0, 19], terrain: "grass", object: null },
//   { id: "18-0", position: [18, 0, 0], terrain: "grass", object: null },
//   { id: "18-1", position: [18, 0, 1], terrain: "grass", object: null },
//   { id: "18-2", position: [18, 0, 2], terrain: "grass", object: null },
//   { id: "18-3", position: [18, 0, 3], terrain: "grass", object: null },
//   { id: "18-4", position: [18, 0, 4], terrain: "grass", object: null },
//   { id: "18-5", position: [18, 0, 5], terrain: "grass", object: null },
//   { id: "18-6", position: [18, 0, 6], terrain: "grass", object: "rock", variant: 1 },
//   { id: "18-7", position: [18, 0, 7], terrain: "grass", object: null },
//   { id: "18-8", position: [18, 0, 8], terrain: "grass", object: null },
//   { id: "18-9", position: [18, 0, 9], terrain: "grass", object: null },
//   { id: "18-10", position: [18, 0, 10], terrain: "grass", object: null },
//   { id: "18-11", position: [18, 0, 11], terrain: "grass", object: null },
//   { id: "18-12", position: [18, 0, 12], terrain: "grass", object: null },
//   { id: "18-13", position: [18, 0, 13], terrain: "grass", object: "tree", variant: 1 },
//   { id: "18-14", position: [18, 0, 14], terrain: "grass", object: null },
//   { id: "18-15", position: [18, 0, 15], terrain: "grass", object: null },
//   { id: "18-16", position: [18, 0, 16], terrain: "grass", object: null },
//   { id: "18-17", position: [18, 0, 17], terrain: "grass", object: null },
//   { id: "18-18", position: [18, 0, 18], terrain: "grass", object: null },
//   { id: "18-19", position: [18, 0, 19], terrain: "grass", object: null },
//   { id: "19-0", position: [19, 0, 0], terrain: "grass", object: null },
//   { id: "19-1", position: [19, 0, 1], terrain: "grass", object: null },
//   { id: "19-2", position: [19, 0, 2], terrain: "grass", object: "rock", variant: 0 },
//   { id: "19-3", position: [19, 0, 3], terrain: "grass", object: null },
//   { id: "19-4", position: [19, 0, 4], terrain: "grass", object: null },
//   { id: "19-5", position: [19, 0, 5], terrain: "grass", object: null },
//   { id: "19-6", position: [19, 0, 6], terrain: "grass", object: null },
//   { id: "19-7", position: [19, 0, 7], terrain: "grass", object: "bush" },
//   { id: "19-8", position: [19, 0, 8], terrain: "grass", object: null },
//   { id: "19-9", position: [19, 0, 9], terrain: "grass", object: null },
//   { id: "19-10", position: [19, 0, 10], terrain: "grass", object: null },
//   { id: "19-11", position: [19, 0, 11], terrain: "grass", object: null },
//   { id: "19-12", position: [19, 0, 12], terrain: "water", object: null },
//   { id: "19-13", position: [19, 0, 13], terrain: "grass", object: null },
//   { id: "19-14", position: [19, 0, 14], terrain: "grass", object: null },
//   { id: "19-15", position: [19, 0, 15], terrain: "grass", object: null },
//   { id: "19-16", position: [19, 0, 16], terrain: "grass", object: null },
//   { id: "19-17", position: [19, 0, 17], terrain: "grass", object: null },
//   { id: "19-18", position: [19, 0, 18], terrain: "grass", object: null },
//   { id: "19-19", position: [19, 0, 19], terrain: "grass", object: null },
// ];

import { MapTile } from '@/core-ui/types/map';

export const competitiveMap: MapTile[] = [
  // Fila 0
  { id: '0-0', position: [0, 0, 0], terrain: 'grass', object: null },
  { id: '1-0', position: [1, 0, 0], terrain: 'grass', object: 'tree', variant: 2 },
  {
    id: '2-0',
    position: [2, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '3-0', position: [3, 0, 0], terrain: 'water', object: null },
  { id: '4-0', position: [4, 0, 0], terrain: 'water', object: null },
  {
    id: '5-0',
    position: [5, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 2,
  },
  {
    id: '6-0',
    position: [6, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  {
    id: '7-0',
    position: [7, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  {
    id: '8-0',
    position: [8, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '9-0', position: [9, 0, 0], terrain: 'water', object: null },

  // Fila 1
  { id: '0-1', position: [0, 0, 1], terrain: 'grass', object: null },
  {
    id: '1-1',
    position: [1, 0, 1],
    terrain: 'grass',
    object: null,
  },
  { id: '2-1', position: [2, 0, 1], terrain: 'grass', object: null },
  { id: '3-1', position: [3, 0, 1], terrain: 'grass', object: null },
  {
    id: '4-1',
    position: [4, 0, 1],
    terrain: 'grass',
    object: 'rock',
    variant: 1,
  },
  { id: '5-1', position: [5, 0, 1], terrain: 'grass', object: 'bush' },
  { id: '6-1', position: [6, 0, 1], terrain: 'grass', object: null },
  { id: '7-1', position: [7, 0, 1], terrain: 'grass', object: null },
  {
    id: '8-1',
    position: [8, 0, 1],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  { id: '9-1', position: [9, 0, 1], terrain: 'water', object: null },

  // Fila 2
  { id: '0-2', position: [0, 0, 2], terrain: 'grass', object: null },
  { id: '1-2', position: [1, 0, 2], terrain: 'grass', object: 'barn' },
  { id: '2-2', position: [2, 0, 2], terrain: 'grass', object: null },
  { id: '3-2', position: [3, 0, 2], terrain: 'grass', object: 'bush' },
  { id: '4-2', position: [4, 0, 2], terrain: 'grass', object: null },
  { id: '5-2', position: [5, 0, 2], terrain: 'grass', object: null },
  {
    id: '6-2',
    position: [6, 0, 2],
    terrain: 'grass',
    object: 'rock',
    variant: 0,
  },
  { id: '7-2', position: [7, 0, 2], terrain: 'grass', object: null },
  { id: '8-2', position: [8, 0, 2], terrain: 'grass', object: null },
  { id: '9-2', position: [9, 0, 2], terrain: 'water', object: null },

  // Fila 3
  { id: '0-3', position: [0, 0, 3], terrain: 'grass', object: null },
  { id: '1-3', position: [1, 0, 3], terrain: 'grass', object: null },
  { id: '2-3', position: [2, 0, 3], terrain: 'grass', object: null },
  {
    id: '3-3',
    position: [3, 0, 3],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '4-3', position: [4, 0, 3], terrain: 'grass', object: null },
  { id: '5-3', position: [5, 0, 3], terrain: 'grass', object: null },
  { id: '6-3', position: [6, 0, 3], terrain: 'grass', object: null },
  { id: '7-3', position: [7, 0, 3], terrain: 'grass', object: null },
  { id: '8-3', position: [8, 0, 3], terrain: 'grass', object: null },
  { id: '9-3', position: [9, 0, 3], terrain: 'water', object: null },

  // Fila 4
  {
    id: '0-4',
    position: [0, 0, 4],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  { id: '1-4', position: [1, 0, 4], terrain: 'grass', object: null },
  { id: '2-4', position: [2, 0, 4], terrain: 'grass', object: null },
  { id: '3-4', position: [3, 0, 4], terrain: 'grass', object: null },
  { id: '4-4', position: [4, 0, 4], terrain: 'grass', object: null },
  { id: '5-4', position: [5, 0, 4], terrain: 'grass', object: null },
  { id: '6-4', position: [6, 0, 4], terrain: 'grass', object: null },
  { id: '7-4', position: [7, 0, 4], terrain: 'grass', object: null },
  { id: '8-4', position: [8, 0, 4], terrain: 'grass', object: null },
  { id: '9-4', position: [9, 0, 4], terrain: 'water', object: null },

  // Fila 5
  { id: '0-5', position: [0, 0, 5], terrain: 'grass', object: null },
  { id: '1-5', position: [1, 0, 5], terrain: 'grass', object: null },
  { id: '2-5', position: [2, 0, 5], terrain: 'grass', object: null },
  { id: '3-5', position: [3, 0, 5], terrain: 'grass', object: null },
  { id: '4-5', position: [4, 0, 5], terrain: 'grass', object: 'bush' },
  {
    id: '5-5',
    position: [5, 0, 5],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '6-5', position: [6, 0, 5], terrain: 'grass', object: null },
  { id: '7-5', position: [7, 0, 5], terrain: 'grass', object: null },
  { id: '8-5', position: [8, 0, 5], terrain: 'grass', object: null },
  { id: '9-5', position: [9, 0, 5], terrain: 'water', object: null },

  // Fila 6
  { id: '0-6', position: [0, 0, 6], terrain: 'water', object: null },
  { id: '1-6', position: [1, 0, 6], terrain: 'grass', object: null },
  {
    id: '2-6',
    position: [2, 0, 6],
    terrain: 'grass',
    object: 'rock',
    variant: 0,
  },
  { id: '3-6', position: [3, 0, 6], terrain: 'grass', object: null },
  { id: '4-6', position: [4, 0, 6], terrain: 'grass', object: null },
  { id: '5-6', position: [5, 0, 6], terrain: 'grass', object: 'bush' },
  {
    id: '6-6',
    position: [6, 0, 6],
    terrain: 'grass',
    object: null,
  },
  { id: '7-6', position: [7, 0, 6], terrain: 'grass', object: 'bank' },
  { id: '8-6', position: [8, 0, 6], terrain: 'grass', object: null },
  { id: '9-6', position: [9, 0, 6], terrain: 'water', object: null },

  // Fila 7
  { id: '0-7', position: [0, 0, 7], terrain: 'water', object: null },
  { id: '1-7', position: [1, 0, 7], terrain: 'grass', object: null },
  { id: '2-7', position: [2, 0, 7], terrain: 'grass', object: null },
  { id: '3-7', position: [3, 0, 7], terrain: 'grass', object: null },
  { id: '4-7', position: [4, 0, 7], terrain: 'grass', object: null },
  { id: '5-7', position: [5, 0, 7], terrain: 'grass', object: null },
  { id: '6-7', position: [6, 0, 7], terrain: 'grass', object: null },
  {
    id: '7-7',
    position: [7, 0, 7],
    terrain: 'grass',
    object: null,
  },
  { id: '8-7', position: [8, 0, 7], terrain: 'grass', object: null },
  { id: '9-7', position: [9, 0, 7], terrain: 'grass', object: 'bush' },

  // Fila 8
  { id: '0-8', position: [0, 0, 8], terrain: 'water', object: null },
  { id: '1-8', position: [1, 0, 8], terrain: 'grass', object: null },
  { id: '2-8', position: [2, 0, 8], terrain: 'grass', object: null },
  { id: '3-8', position: [3, 0, 8], terrain: 'grass', object: null },
  { id: '4-8', position: [4, 0, 8], terrain: 'grass', object: null },
  { id: '5-8', position: [5, 0, 8], terrain: 'grass', object: null },
  { id: '6-8', position: [6, 0, 8], terrain: 'grass', object: null },
  { id: '7-8', position: [7, 0, 8], terrain: 'grass', object: null },
  { id: '8-8', position: [8, 0, 8], terrain: 'grass', object: null },
  { id: '9-8', position: [9, 0, 8], terrain: 'grass', object: null },

  // Fila 9
  { id: '0-9', position: [0, 0, 9], terrain: 'water', object: null },
  { id: '1-9', position: [1, 0, 9], terrain: 'water', object: null },
  { id: '2-9', position: [2, 0, 9], terrain: 'water', object: null },
  { id: '3-9', position: [3, 0, 9], terrain: 'grass', object: null },
  { id: '4-9', position: [4, 0, 9], terrain: 'grass', object: null },
  { id: '5-9', position: [5, 0, 9], terrain: 'grass', object: null },
  { id: '6-9', position: [6, 0, 9], terrain: 'grass', object: null },
  {
    id: '7-9',
    position: [7, 0, 9],
    terrain: 'grass',
    object: 'rock',
    variant: 1,
  },
  {
    id: '8-9',
    position: [8, 0, 9],
    terrain: 'grass',
    object: 'tree',
    variant: 2,
  },
  { id: '9-9', position: [9, 0, 9], terrain: 'grass', object: 'bush' },
];
