import { MapTile } from '@/core-ui/types/map';

export const competitiveMap: MapTile[] = [
  // Fila 0
  { id: '0-0', position: [0, 0, 0], terrain: 'grass', object: null },
  { id: '1-0', position: [1, 0, 0], terrain: 'grass', object: 'tree', variant: 2 },
  {
    id: '2-0',
    position: [2, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '3-0', position: [3, 0, 0], terrain: 'water', object: null },
  { id: '4-0', position: [4, 0, 0], terrain: 'water', object: null },
  {
    id: '5-0',
    position: [5, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 2,
  },
  {
    id: '6-0',
    position: [6, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  {
    id: '7-0',
    position: [7, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  {
    id: '8-0',
    position: [8, 0, 0],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '9-0', position: [9, 0, 0], terrain: 'water', object: null },

  // Fila 1
  { id: '0-1', position: [0, 0, 1], terrain: 'grass', object: null },
  {
    id: '1-1',
    position: [1, 0, 1],
    terrain: 'grass',
    object: null,
  },
  { id: '2-1', position: [2, 0, 1], terrain: 'grass', object: null },
  { id: '3-1', position: [3, 0, 1], terrain: 'grass', object: null },
  {
    id: '4-1',
    position: [4, 0, 1],
    terrain: 'grass',
    object: 'rock',
    variant: 1,
  },
  { id: '5-1', position: [5, 0, 1], terrain: 'grass', object: 'bush' },
  { id: '6-1', position: [6, 0, 1], terrain: 'grass', object: null },
  { id: '7-1', position: [7, 0, 1], terrain: 'grass', object: null },
  {
    id: '8-1',
    position: [8, 0, 1],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  { id: '9-1', position: [9, 0, 1], terrain: 'water', object: null },

  // Fila 2
  { id: '0-2', position: [0, 0, 2], terrain: 'grass', object: null },
  { id: '1-2', position: [1, 0, 2], terrain: 'grass', object: null },
  { id: '2-2', position: [2, 0, 2], terrain: 'grass', object: null },
  { id: '3-2', position: [3, 0, 2], terrain: 'grass', object: 'bush' },
  { id: '4-2', position: [4, 0, 2], terrain: 'grass', object: null },
  { id: '5-2', position: [5, 0, 2], terrain: 'grass', object: null },
  {
    id: '6-2',
    position: [6, 0, 2],
    terrain: 'grass',
    object: 'rock',
    variant: 0,
  },
  { id: '7-2', position: [7, 0, 2], terrain: 'grass', object: null },
  { id: '8-2', position: [8, 0, 2], terrain: 'grass', object: null },
  { id: '9-2', position: [9, 0, 2], terrain: 'water', object: null },

  // Fila 3
  { id: '0-3', position: [0, 0, 3], terrain: 'grass', object: null },
  { id: '1-3', position: [1, 0, 3], terrain: 'grass', object: null },
  { id: '2-3', position: [2, 0, 3], terrain: 'grass', object: null },
  {
    id: '3-3',
    position: [3, 0, 3],
    terrain: 'grass',
    object: null,
  },
  { id: '4-3', position: [4, 0, 3], terrain: 'grass', object: null },
  { id: '5-3', position: [5, 0, 3], terrain: 'grass', object: null },
  { id: '6-3', position: [6, 0, 3], terrain: 'grass', object: null },
  { id: '7-3', position: [7, 0, 3], terrain: 'grass', object: null },
  { id: '8-3', position: [8, 0, 3], terrain: 'grass', object: null },
  { id: '9-3', position: [9, 0, 3], terrain: 'water', object: null },

  // Fila 4
  {
    id: '0-4',
    position: [0, 0, 4],
    terrain: 'grass',
    object: 'tree',
    variant: 1,
  },
  { id: '1-4', position: [1, 0, 4], terrain: 'grass', object: 'tree', variant: 2 },
  { id: '2-4', position: [2, 0, 4], terrain: 'grass', object: 'barn' },
  { id: '3-4', position: [3, 0, 4], terrain: 'grass', object: null },
  { id: '4-4', position: [4, 0, 4], terrain: 'grass', object: null },
  { id: '5-4', position: [5, 0, 4], terrain: 'grass', object: null },
  { id: '6-4', position: [6, 0, 4], terrain: 'grass', object: null },
  { id: '7-4', position: [7, 0, 4], terrain: 'grass', object: null },
  { id: '8-4', position: [8, 0, 4], terrain: 'grass', object: null },
  { id: '9-4', position: [9, 0, 4], terrain: 'water', object: null },

  // Fila 5
  { id: '0-5', position: [0, 0, 5], terrain: 'grass', object: null },
  { id: '1-5', position: [1, 0, 5], terrain: 'grass', object: null },
  { id: '2-5', position: [2, 0, 5], terrain: 'grass', object: null },
  { id: '3-5', position: [3, 0, 5], terrain: 'grass', object: null },
  { id: '4-5', position: [4, 0, 5], terrain: 'grass', object: null },
  {
    id: '5-5',
    position: [5, 0, 5],
    terrain: 'grass',
    object: 'leaderboard',
    variant: 0,
  },
  { id: '6-5', position: [6, 0, 5], terrain: 'grass', object: null },
  { id: '7-5', position: [7, 0, 5], terrain: 'grass', object: null },
  { id: '8-5', position: [8, 0, 5], terrain: 'grass', object: null },
  { id: '9-5', position: [9, 0, 5], terrain: 'water', object: null },

  // Fila 6
  { id: '0-6', position: [0, 0, 6], terrain: 'water', object: null },
  { id: '1-6', position: [1, 0, 6], terrain: 'grass', object: null },
  {
    id: '2-6',
    position: [2, 0, 6],
    terrain: 'grass',
    object: 'tree',
    variant: 0,
  },
  { id: '3-6', position: [3, 0, 6], terrain: 'grass', object: null },
  { id: '4-6', position: [4, 0, 6], terrain: 'grass', object: null },
  { id: '5-6', position: [5, 0, 6], terrain: 'grass', object: null },
  {
    id: '6-6',
    position: [6, 0, 6],
    terrain: 'grass',
    object: null,
  },
  { id: '7-6', position: [7, 0, 6], terrain: 'grass', object: 'bank' },
  { id: '8-6', position: [8, 0, 6], terrain: 'grass', object: null },
  { id: '9-6', position: [9, 0, 6], terrain: 'water', object: null },

  // Fila 7
  { id: '0-7', position: [0, 0, 7], terrain: 'water', object: null },
  { id: '1-7', position: [1, 0, 7], terrain: 'grass', object: null },
  { id: '2-7', position: [2, 0, 7], terrain: 'grass', object: null },
  { id: '3-7', position: [3, 0, 7], terrain: 'grass', object: null },
  { id: '4-7', position: [4, 0, 7], terrain: 'grass', object: null },
  { id: '5-7', position: [5, 0, 7], terrain: 'grass', object: null },
  { id: '6-7', position: [6, 0, 7], terrain: 'grass', object: null },
  {
    id: '7-7',
    position: [7, 0, 7],
    terrain: 'grass',
    object: null,
  },
  { id: '8-7', position: [8, 0, 7], terrain: 'grass', object: null },
  { id: '9-7', position: [9, 0, 7], terrain: 'grass', object: 'bush' },

  // Fila 8
  { id: '0-8', position: [0, 0, 8], terrain: 'water', object: null },
  { id: '1-8', position: [1, 0, 8], terrain: 'grass', object: null },
  { id: '2-8', position: [2, 0, 8], terrain: 'grass', object: null },
  { id: '3-8', position: [3, 0, 8], terrain: 'grass', object: null },
  { id: '4-8', position: [4, 0, 8], terrain: 'grass', object: null },
  { id: '5-8', position: [5, 0, 8], terrain: 'grass', object: null },
  { id: '6-8', position: [6, 0, 8], terrain: 'grass', object: null },
  { id: '7-8', position: [7, 0, 8], terrain: 'grass', object: null },
  { id: '8-8', position: [8, 0, 8], terrain: 'grass', object: null },
  { id: '9-8', position: [9, 0, 8], terrain: 'grass', object: null },

  // Fila 9
  { id: '0-9', position: [0, 0, 9], terrain: 'water', object: null },
  { id: '1-9', position: [1, 0, 9], terrain: 'water', object: null },
  { id: '2-9', position: [2, 0, 9], terrain: 'water', object: null },
  { id: '3-9', position: [3, 0, 9], terrain: 'grass', object: null },
  { id: '4-9', position: [4, 0, 9], terrain: 'grass', object: null },
  { id: '5-9', position: [5, 0, 9], terrain: 'grass', object: null },
  { id: '6-9', position: [6, 0, 9], terrain: 'grass', object: null },
  {
    id: '7-9',
    position: [7, 0, 9],
    terrain: 'grass',
    object: 'rock',
    variant: 1,
  },
  {
    id: '8-9',
    position: [8, 0, 9],
    terrain: 'grass',
    object: 'tree',
    variant: 2,
  },
  { id: '9-9', position: [9, 0, 9], terrain: 'grass', object: 'bush' },
];
