services:
  node_app:
    build:
      context: .
      dockerfile: config/api-app.Dockerfile
    container_name: node_app
    environment:
      NODE_ENV: production
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # solo HTTP por ahora
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - node_app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
