services:
  initial_nginx:
    image: nginx:latest
    container_name: initial_nginx
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./config/initial_nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
